groups:
  - name: morphsave.application
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
          service: morphsave
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: morphsave
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.instance }}"

      # Application down
      - alert: ApplicationDown
        expr: up{job="morphsave-app"} == 0
        for: 1m
        labels:
          severity: critical
          service: morphsave
        annotations:
          summary: "MorphSave application is down"
          description: "Application {{ $labels.instance }} has been down for more than 1 minute"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes / process_virtual_memory_max_bytes) > 0.8
        for: 5m
        labels:
          severity: warning
          service: morphsave
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

      # Database connection issues
      - alert: DatabaseConnectionFailure
        expr: increase(database_connection_errors_total[5m]) > 5
        for: 2m
        labels:
          severity: critical
          service: morphsave
        annotations:
          summary: "Database connection failures"
          description: "{{ $value }} database connection failures in the last 5 minutes"

      # Blockchain transaction failures
      - alert: BlockchainTransactionFailures
        expr: increase(blockchain_transaction_failures_total[10m]) > 3
        for: 5m
        labels:
          severity: warning
          service: morphsave
        annotations:
          summary: "Blockchain transaction failures"
          description: "{{ $value }} blockchain transaction failures in the last 10 minutes"

      # Low user activity
      - alert: LowUserActivity
        expr: rate(user_actions_total[1h]) < 10
        for: 30m
        labels:
          severity: warning
          service: morphsave
        annotations:
          summary: "Low user activity detected"
          description: "User activity rate is {{ $value }} actions per second over the last hour"

      # High queue depth
      - alert: HighQueueDepth
        expr: queue_depth > 1000
        for: 5m
        labels:
          severity: warning
          service: morphsave
        annotations:
          summary: "High queue depth"
          description: "Queue depth is {{ $value }} for {{ $labels.queue_name }}"

  - name: morphsave.infrastructure
    rules:
      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      # High disk usage
      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.85
        for: 5m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "High disk usage"
          description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

      # PostgreSQL down
      - alert: PostgreSQLDown
        expr: up{job="postgres-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been down for more than 1 minute"

      # Redis down
      - alert: RedisDown
        expr: up{job="redis-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: cache
        annotations:
          summary: "Redis is down"
          description: "Redis cache has been down for more than 1 minute"

      # High database connections
      - alert: HighDatabaseConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "High database connections"
          description: "Database connections are at {{ $value | humanizePercentage }} of maximum"

  - name: morphsave.security
    rules:
      # High failed login attempts
      - alert: HighFailedLogins
        expr: increase(auth_failed_attempts_total[5m]) > 50
        for: 2m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "High failed login attempts"
          description: "{{ $value }} failed login attempts in the last 5 minutes"

      # Rate limit exceeded
      - alert: RateLimitExceeded
        expr: increase(rate_limit_exceeded_total[5m]) > 100
        for: 2m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "Rate limit frequently exceeded"
          description: "Rate limit exceeded {{ $value }} times in the last 5 minutes"

      # Suspicious wallet activity
      - alert: SuspiciousWalletActivity
        expr: increase(wallet_security_alerts_total[10m]) > 0
        for: 1m
        labels:
          severity: critical
          service: security
        annotations:
          summary: "Suspicious wallet activity detected"
          description: "{{ $value }} wallet security alerts in the last 10 minutes"